{{- $host := pluck .Values.werf.env .Values.host | first | default .Values.host._default  }}
{{- if  hasPrefix "review" .Values.werf.env }}
{{- $host = ( printf "%s.%s" .Values.werf.env (pluck "dev" .Values.host | first | default .Values.host._default ) | lower ) }}
{{- end }}
{{- $ingressClassName := pluck .Values.global.env .Values.ingressClassName | first | default .Values.ingressClassName._default | quote }}
{{- $ruHostPattern := pluck .Values.global.env .Values.ruHostPattern | first | default .Values.ruHostPattern._default }}
{{- $ruHost := printf $ruHostPattern $host }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tuf-router
  annotations:
spec:
  ingressClassName: {{ $ingressClassName }}
  tls:
  - hosts:
      - {{ $host }}
      - {{ $ruHost }}
    secretName: tls-{{ $host }}
  rules:
  - host: {{ $host }}
    http:
      paths:
      - path: /targets
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
      - path: /download
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
  - host: {{ $ruHost }}
    http:
      paths:
      - path: /targets
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
      - path: /download
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
