priorityClassName:
  _default: develop
  production: production-medium

host:
  production: trdl.dev
  _default: trdl.test.flant.dev

ingressClassName:
  _default: "nginx"
  production: "standalone-geo"

ruHostPattern:
  production: "ru.%s"
  _default: "ru-%s"

resources:
  requests:
    memory:
      _default: 20M
      production: 50M
